### ISSUE TITLE
`Comments` with `PostID` not filtered by given post ID

### ISSUE THREAD

**Issue by mrusme** [Arsen6331/go-lemmy#1]
I'm trying to retrieve all comments for a specific post, hence I've been trying out different sorts of variations of this code:

```go
	resp, err := sys.client.Comments(context.Background(), types.GetComments{
		Type: types.NewOptional(types.ListingLocal),
		Sort: types.NewOptional(types.CommentSortHot),
		// CommunityID: types.NewOptional(cid),
		PostID: types.NewOptional(pid),
	})
```

The `pid` is the correct post ID, yet the comments that I'm getting back seem to be simply the listing of *all* new local comments. I'm not quite sure what's going on there as it seems to me that changing different parameters won't alter the server's response in any way.

Maybe you might have idea of what's going on? I might very well just be *holding it wrong*.

**Comment by Elara6331** [comment]
Sorry for the late response, it was new year and I didn't have much time. I'll try to figure out what's going on here and get back to you, thanks.

**Comment by Elara6331** [comment]
Interestingly, it is sending `post_id=458247` (I'm using post ID 458247 for testing) to the server, but it seems that's ignored for some reason.

**Comment by Elara6331** [comment]
The way Lemmy's UI seems to do it is they use `getPost()` and then check the `comments` field that's returned, but the Rust and JS structs don't have a comments field, so I'm not sure how that gets returned.

**Comment by mrusme** [comment]
Maybe @dessalines might be able to help here? Would be cool to get this working, currently having a new Lemmy client in the works and this library saved my poor ass from having to implement all this on my own. :-)

Specifically, quote:

> sending post_id=458247 (I'm using post ID 458247 for testing) to the server, but it seems that's ignored for some reason.

**Comment by dessalines** [comment]
https://join-lemmy.org/api/classes/LemmyHttp.html#getPost

@Arsen6331 the current `main` of lemmy / lemmy-js-client has a lot of API changes that haven't been deployed yet.

**Comment by Elara6331** [comment]
> [join-lemmy.org/api/classes/LemmyHttp.html#getPost](https://join-lemmy.org/api/classes/LemmyHttp.html#getPost)
> 
> @Arsen6331 the current `main` of lemmy / lemmy-js-client has a lot of API changes that haven't been deployed yet.

I looked at the LemmyHttp docs, and neither `getPost` nor `getPosts` appear to return comments.

![image](https://user-images.githubusercontent.com/41810442/210677183-a5a7cd9f-abfd-4987-a6b7-900ba353c68c.png)

**Comment by dessalines** [comment]
Ah my bad, that must be showing the RC unfortunately. 

Here you go:

https://github.com/LemmyNet/lemmy-js-client/blob/0.16.4/src/interfaces/api/post.ts#L29

https://github.com/LemmyNet/joinlemmy-site/issues/123

**Comment by Elara6331** [comment]
The conversion done for this library is only partially automated, so if the API changes this much, it's going to become very difficult to maintain very quickly. To solve that, I'm working on a completely automated converter right now that I will use to automatically generate bindings for the latest release once it's done (should be pretty soon).

**Comment by mrusme** [comment]
Is there a quickfix that can be used up until then however?

**Comment by Elara6331** [comment]
You can try adding a `comments` field to the `GetPostResponse` struct, but there are likely other issues you'll encounter.

**Comment by Elara6331** [comment]
The bindings are now completely automatically generated for v0.16.7. Can you try them and see if it fixes your issue? @mrusme

The `Login()` function has been renamed to `ClientLogin()`,

You have to use `Post()`, which will return `GetPostResponse`, which will have the comments, because that's the way the current API does it.

**Comment by mrusme** [comment]
@Arsen6331 it seems that now types (e.g. `ListingTypeSubscribe`) are a bit messed up:

```
cannot use types.NewOptional(types.ListingTypeSubscribed) (value of type types.Optional[string]) as type types.Optional[types.ListingType] in struct literal
```

**Comment by Elara6331** [comment]
Ah, I forgot to use the type I created. Can you try now? It should be fixed.

**Comment by mrusme** [comment]
~~Are you sure `go.arsenm.dev/go-lemmy` is updating properly? I can see your commits here but I'm using the package as it was defined in its go mod.~~ Updated, checking.

**Comment by mrusme** [comment]
It seems the internal time.Time parsing doesn't work yet:

```
parsing time "\"2022-12-29T01:39:01.346720\"" as "\"2006-01-02T15:04:05Z07:00\"": cannot parse "\"" as "Z07:00"
```

That's what I'm doing:

```go
	resp, err := sys.client.Posts(context.Background(), types.GetPosts{
		Type:  types.NewOptional(types.ListingTypeSubscribed),
		Sort:  types.NewOptional(types.SortTypeNew),
		Limit: types.NewOptional(int64(50)),
	})
```

**Comment by Elara6331** [comment]
Just fixed that, should be working now

**Comment by mrusme** [comment]
Awesome work! Can retrieve the correct comments now. 👍🏼 Very nice, thank you very much!
